services:
  - type: web
    name: Translation-App
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
